### PR TITLE
Add MobileNetV3-Small and EfficientNet for vision data

### PR DESCRIPTION
**Pull request by ilos-vigil**
PR for point 2 which mentioned on issue https://github.com/amaiya/ktrain/issues/406#issuecomment-998025286

Test result: https://colab.research.google.com/drive/1EJHpMVG6fBCg33UPla_Ly_6LQdswU2Ur?usp=sharing

Other change:
* Add paper link for some vision model
* Update documentation on function which obtain vision model

### CODE REVIEW

**Comment by amaiya** [comment]
Great! It has been merged - thank you!

**Comment by amaiya** [comment]
Hi @ilos-vigil : Just a quick FYI. It looks like MobileNetV3 isn't supported by older versions of TensorFlow (e.g., 2.3.x), so I added a check for backwards compatibility in the `develop` branch: 08c8a7172591772b2f30e6e58572e9e1b001ef41

**Comment by ilos-vigil** [comment]
> Hi @ilos-vigil : Just a quick FYI. It looks like MobileNetV3 isn't supported by older versions of TensorFlow (e.g., 2.3.x), so I added a check for backwards compatibility in the `develop` branch: [08c8a71](https://github.com/amaiya/ktrain/commit/08c8a7172591772b2f30e6e58572e9e1b001ef41)

I see. I don't know earliest version of TF2 you're willing to support, but FYI EfficientNet only available since TF 2.3.

**Comment by amaiya** [comment]
OK- that's good to know.  **ktrain** used to support any version of TF 2, but, at some point, `transformers` stopped supporting TF 2.1 and below.  I know the current  supported versions of `transformers` used by ktrain supports TF 2.3 and above, so I've edited the installation instructions in the README about needing a TF version at or above TF 2.3. Thanks for pointing this out.

**Pull request merged**
