### PR TITLE
Fix predict_generator to return probabilities if return_proba==True

### PR DESCRIPTION
**Pull request by lutich**
Small, but annoying typo in vision's predict_generator. Hope you would be ok with it. Thx, Andrey

### CODE REVIEW

**Comment by amaiya** [comment]
@lutich Great - thanks.  I'll merge this, but had a question about it.  It sounds like the original problem was that, for multilabel problems, `return_proba=True` had no effect and class labels were always included in the result.  If this is the case, I'm wondering if there needs to be additional changes.  For instance, after your PR, the code looks like this:

```python
result =  preds if return_proba else [self.c[np.argmax(pred)] for pred in preds]
 if multilabel and not return_proba:
       return [list(zip(self.c, r)) for r in result]  # code block 1
  else:
       return result                                        # code block 2
```
However, a few lines above, there's this: `if multilabel: return_proba=True` (line 119), which means **code block 1** will never execute.  So, it sounds like that line 119 should be removed and the `result = ...` line should be changed as follows:

```python
result =  preds if return_proba or multilabel else [self.c[np.argmax(pred)] for pred in preds]
```

Sound correct to you?

**Comment by lutich** [comment]
Thanks for prompt reply. Indeed, the **code block 1** would never get executed. I'm not sure I understand why the multilabel case needs separate treatment in this context. 

I would suggest:
```
    def predict_generator(self, generator, steps=None, return_proba=False):
        classification, multilabel = U.is_classifier(self.model)
        preds =  self.model.predict_generator(generator, steps=steps)
        result =  preds if return_proba else [self.c[np.argmax(pred)] for pred in preds]
        return result
```
What do you think?

By the way, the `self.c` seems to be undefined sometimes, while it comes from preproc, which can be None. 

Also in vision/data.py should be `classes = list(map(str, range(len(y_train[0]))))` instead of `classes = map(str, list(range(len(y_train[0]))))`

Should I sumbit a sepater PR for it?

**Comment by amaiya** [comment]
1. The `multilabel` case needs to be treated differently because the prediction should never be reduced to a single label even when `return_proba=False`. So, the existing functionality should probably stay in place for that. As far as this PR, I'm going to go ahead and merge your change with slight additions I mentioned earlier and will test it. (Thank you!)
2.  Yes, that line needs to be changed in `vision/data`.  It is for `images_from_array`, which typically isn't used much other than example datasets like MNIST and CIFAR10 (by me, at least).  If you'd like to open a separate PR for that, that'd be fantastic.
3. Are there other instances where `self.c` is None or otherwise not set correctly?  If so, perhaps you can you tell me which `images_from*` function was used to cause the problem, so it can be fixed.

Thanks again for the contributions.

**Comment by lutich** [comment]
1. OK, probably we just see it differently. My intuition expects the most likely category if the `return_proba=False` is passed. The only difference between `multilabel` and `non-multilabel` is that the later is normalized to 1. `argmax` in both cases would work identically. It is up to you to decide ;) I'm interested in probabilities.

2. (3) Thanks! Yes, I use `images_from_array`. I'll make a proposal for it. All other images_from_* look OK at the first glance. I did not use them yet.

**Pull request merged**
